import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';

// Green satellite images generated by scripts/green-shots.ts, served per
// course-hole id. The manifest maps holeId → filename.
const DIR = resolve(process.cwd(), 'green-shots');
const MANIFEST = resolve(DIR, 'manifest.json');

let map: Map<string, string> | null = null;

function load(): Map<string, string> {
  if (map) return map;
  map = new Map();
  try {
    const entries = JSON.parse(readFileSync(MANIFEST, 'utf8')) as Array<{ holeId?: string; file?: string }>;
    for (const e of entries) if (e.holeId && e.file) map.set(e.holeId, e.file);
  } catch {
    // No images generated yet — map stays empty.
  }
  return map;
}

export const greenImages = {
  has(holeId: string): boolean {
    return load().has(holeId);
  },
  /** Absolute path to the PNG for a hole, or null if there isn't one. */
  filePath(holeId: string): string | null {
    const file = load().get(holeId);
    if (!file) return null;
    const p = resolve(DIR, file);
    return existsSync(p) ? p : null;
  },
  /** Force a re-read (after regenerating images without restarting). */
  reload(): void {
    map = null;
  }
};
